# Generated by Django 5.1.3 on 2025-04-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtherStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField(auto_created=True)),
                ('name', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=30)),
                ('passby', models.IntegerField()),
            ],
        ),
    ]
